namespace FrameworkAPI.Schema.Misc;

/// <summary>
/// Detailed information from the print inspection systems.
/// </summary>
public class PrintInspectionSystemJobData(string proControlInternalJobId, PrintInspectionSystemsStatus status)
{

    /// <summary>
    /// Unique id of the job, which was generated by the machine.
    /// This internal id of ProControl is needed to get the data from the print inspection system database.
    /// [Source: CheckDataHandler]
    /// </summary>
    public string ProControlInternalJobId { get; set; } = proControlInternalJobId;

    /// <summary>
    /// Status of the print inspection systems.
    /// [Source: CheckDataHandler]
    /// </summary>
    public PrintInspectionSystemsStatus Status { get; set; } = status;
}