namespace FrameworkAPI.Schema.Misc;

/// <summary>
/// Detailed information from the print inspection systems.
/// </summary>
public class PrintInspectionSystemRollData(string proControlInternalRollId, PrintInspectionSystemsStatus status)
{

    /// <summary>
    /// Unique id of the roll, which was generated by the machine.
    /// This internal id of ProControl is needed to get the data from the print inspection system database.
    /// [Source: CheckDataHandler]
    /// </summary>
    public string ProControlInternalRollId { get; set; } = proControlInternalRollId;

    /// <summary>
    /// Status of the print inspection systems.
    /// [Source: CheckDataHandler]
    /// </summary>
    public PrintInspectionSystemsStatus Status { get; set; } = status;
}